import Header from "@/components/Header";
import {SanityLive} from "@/sanity/lib/live";
import {ClerkProvider} from "@clerk/nextjs";
import type {Metadata} from "next";
import "../globals.css";

import DisableDraftMode from "@/components/DisableDraftMode";
import {VisualEditing} from "next-sanity";
import {draftMode} from "next/headers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider dynamic>
      <html lang="en">
        <body>
          {(await draftMode()).isEnabled && (
            <>
              <DisableDraftMode />
              <VisualEditing />
            </>
          )}
          <main>
            <Header />
            {children}
          </main>
          <SanityLive />
        </body>
      </html>
    </ClerkProvider>
  );
}
